runtime: python27
version: 1
api_version: 1
application: cosmopolite-root
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    X-Frame-Options: DENY
    X-Content-Type-Options: nosniff
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /tutorial
  static_files: tutorial.html
  upload: tutorial.html
  secure: always
  http_headers:
    X-Frame-Options: DENY
    X-Content-Type-Options: nosniff
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /images
  static_dir: images
  secure: always
  http_headers:
    X-Frame-Options: DENY
    X-Content-Type-Options: nosniff
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /stylesheets
  static_dir: stylesheets
  secure: always
  http_headers:
    X-Frame-Options: DENY
    X-Content-Type-Options: nosniff
    Strict-Transport-Security: max-age=31536000; includeSubDomains
